// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DeleteTodo(arg1:number):Promise<void>;

export function GetHostName():Promise<string>;

export function GetTodos():Promise<Array<domain.Todo>>;

export function Greet(arg1:string):Promise<string>;

export function InsertTodo(arg1:domain.Todo):Promise<number>;

export function ListTodos():Promise<Array<domain.Todo>>;

export function UpdateTodo(arg1:domain.Todo):Promise<void>;
