// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetHostName() {
  return window['go']['main']['App']['GetHostName']();
}

export function GetTodos() {
  return window['go']['main']['App']['GetTodos']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertTodo(arg1) {
  return window['go']['main']['App']['InsertTodo'](arg1);
}

export function ListTodos() {
  return window['go']['main']['App']['ListTodos']();
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}
